### ISSUE TITLE
Cannot parse https://www.w3.org/ns/auth/acl#

### ISSUE THREAD

**Issue by gfellerph** [blake-regalia/graphy.js#11]
It seems the turtle parser does not like tripple apostrophes like `"""`, in use at https://www.w3.org/ns/auth/acl#.  The RDF validator at https://www.w3.org/2015/03/ShExValidata/ however states that the turtle document is formatted propperly.

The error:

```
expected: post_object
parser.js:373
index.mjs:85
`"Append accesses are specific `
 ^
expected post_object.  failed to parse a valid token starting at """
```

**Comment by blake-regalia** [comment]
Thanks for the report. This is fixed in v3.0.0 which is nearly ready for release. Stay tuned and I will close this issue once it's published.
