### ISSUE TITLE
Fails on long literals

### ISSUE THREAD

**Issue by RubenVerborgh** [blake-regalia/graphy.js#13]
I noticed that the graphy Turtle and N-triples parsers fail on [`long.nt`](https://github.com/rdfjs/N3.js/issues/128#issuecomment-555487408), on which N3.js was failing as well.

With the N-Triples parser, it fails with `Maximum call stack size exceeded`.
With the Turtle parser, it fails with `failed to parse a valid token starting at """`.

**Comment by RubenVerborgh** [comment]
Alo for the TriG parser on `out_1000000_points.trig` in that same issue; fails with `failed to parse a valid token starting at """`.

**Comment by blake-regalia** [comment]
This is a builtin fail-safe for recovering from syntax errors in endless streams controlled by the `maxStringLength` key in the [read config](https://graphy.link/content.textual#config_read-no-input). Setting this config value to `Infinity` handles these cases accordingly.

> maxStringLength : number=65536 – defines the maximum number of characters to expect of any quoted literal. This option only exists to prevent invalid input from endlessly consuming the reader (such as a long-quoted literal """ that never ends...) when using a stream as input. By default, this value is set to 65536 characters. However, you may set this value to Infinity if you never expect to encounter invalid syntax on the input stream.

**Comment by RubenVerborgh** [comment]
👌 thanks

**Comment by RubenVerborgh** [comment]
With `Infinity`, I get `Maximum call stack size exceeded` for TriG, N-Triples, and Turtle (instead of `failed to parse a valid token`).

Additional suggestion: perhaps hint at `maxStringLength` in the error message?

**Comment by RubenVerborgh** [comment]
FWIW This is what I did: https://github.com/rdfjs/N3.js/commit/ba26167beb9d964f653412c9388f82f5eee2af46; I found `indexOf` to be much faster than anything else. I then also cached the last checked position (https://github.com/rdfjs/N3.js/commit/5531b092c7968cb7eb08cc0cc925621a1f4f1e67) to avoid re-doing work when new data arrives.

**Comment by blake-regalia** [comment]
This slipped off my radar before the major release. Working on the fix now.

**Comment by blake-regalia** [comment]
Fixed in v4.0.1

@LaurensRietveld
