### ISSUE TITLE
Unable to install Error E404

### ISSUE THREAD

**Issue by houghtonap** [blake-regalia/graphy.js#25]
I tried to install graphy from npm per the instructions and got:
```text
npm install --save graphy
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@graphy%2fcore.iso.threads - Not found
npm ERR! 404
npm ERR! 404  '@graphy/core.iso.threads@4.2.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'graphy'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     AppData\Roaming\npm-cache\_logs\2020-05-05T12_09_58_413Z-debug.log
```

**Comment by blake-regalia** [comment]
Thanks for opening the issue! The latest minor version added a new core package that I forgot to add to the publish script.

I went ahead and fixed this and also removed an unused dependency that might interfere with installation on some platforms: [v4.2.1](https://github.com/blake-regalia/graphy.js/blob/master/CHANGELOG.md#v421-2020-05-05)

Please try again and let me know how it goes.

**Comment by houghtonap** [comment]
Installed without issue on windows 7 x64. Thanks for the quick response, please close issue.
________________________________
