### ISSUE TITLE
XML Scriber does not normalize RDFJS quads from other libs

### ISSUE THREAD

**Issue by blake-regalia** [blake-regalia/graphy.js#31]
`XML_Serializer$pair` expects terms to be graphy without normalization.

**Comment by tpluscode** [comment]
Is this why I got `Not allowed to serialize term type 'NamedNode' as object in XML serializer.` trying to serialize to RDF/XML?

The input was plain RDF/JS quad stream but the serialiser expect `#isNamedNode` getter which obviously does not exist

**Comment by blake-regalia** [comment]
Exactly. I will get this patched before end-of-week.
