### ISSUE TITLE
this._dc_factory.boolean is not a function when parsing boolean in turtle

### ISSUE THREAD

**Issue by tpluscode** [blake-regalia/graphy.js#47]
Error reported in https://github.com/zazuko/shacl-playground/issues/16 turns out to originate from `@graphy/content.trig.read`

This simple list will fail to parse with error `this._dc_factory.boolean is not a function`

```turtle
<A> <b> ( true ) .
```

Here's an example: https://runkit.com/embed/f9em8a0ivl2q

**Comment by blake-regalia** [comment]
Thanks for opening the issue. I should have a patch out by later today.
