### ISSUE TITLE
Add full test suites for NT and NQ parsers

### ISSUE THREAD

**Issue by blake-regalia** [blake-regalia/graphy.js#5]
The NT and NQ parsers need to have test cases for at least the full suites given at https://www.w3.org/2013/N-TriplesTests/ and https://www.w3.org/2013/N-QuadsTests/ .

**Comment by blake-regalia** [comment]
e.g., https://github.com/blake-regalia/graphy.js/issues/3 and https://github.com/blake-regalia/graphy.js/issues/4

**Comment by LaurensRietveld** [comment]
What about simply borrowing  the N3 parser test suite of @RubenVerborgh for this? 
With some small modifications that one should work fine.
Got the impression there are some trivial bugs left that can be detected with this test suite

**Comment by RubenVerborgh** [comment]
There's actually two things you can borrow:
- the unit tests [https://github.com/RubenVerborgh/N3.js/tree/v0.8.5/test]
- the specification tests [https://github.com/RubenVerborgh/N3.js/tree/v0.8.5/spec], which run the W3C test suites

I suppose you would only have to account for the fact that you will have more false positives.

**Comment by blake-regalia** [comment]
Indeed. The start of a "SpecTester" equivalent made its way into the dev branch at [https://github.com/blake-regalia/graphy.js/blob/master/test/specs/turtle-tests.js](test/specs/turtle-test.js) but didn't get finished yet. The thing is that the test results order blank node labels differently than the way graphy creates them (along with a few other discrepancies) which is why I couldn't simply plug-and-play N3.js' test suite. Once there is a 'SpecTester' though, it'll be safe to call the parsers stable.

**Comment by RubenVerborgh** [comment]
The spec tests should work seamlessly though, as they use SWObjects to verify graph isomorphism, so order-independent.
