### ISSUE TITLE
memory.dataset.fast minus omitting results

### ISSUE THREAD

**Issue by MikiDi** [blake-regalia/graphy.js#59]
Hi,

Thanks for making graphy open source!

We're noticing something odd with `memory.dataset.fast`'s [`minus`](https://graphy.link/memory.dataset.fast#method_minus)-method.  
Consider `A.minus(B)`. For cases where set `A` contains a quad with _a subject that occurs in `B`, but a predicate that doesn't occur in `B` for that subject_, those quads are omitted from the result, where we do expect them.

I couldn't get the whole test suite running, so I wrote a small reproduction with a failing test-set similar to that in the graphy test-suite. You can find it [here](
https://github.com/MikiDi/graphy-minus-repro/blob/e71dd0939dfa79f9b91ce289cafd11d721c682d3/app.js#L29-L43).

Thanks!

Michaël

**Comment by MikiDi** [comment]
Hi @blake-regalia , we figure the issue should be situated somewhere around [here](https://github.com/blake-regalia/graphy.js/blob/fc1c231169a5b80dd9d15f0e3d52dd375cd7284c/src/memory/dataset/fast.js.jmacs#L2812-L2861). Is it the `non-empty pairs remainder`-part that is supposed to handle the failing case? Any hints? :slightly_smiling_face:

**Comment by blake-regalia** [comment]
Apologies for the delay. Looking into this now.

**Comment by blake-regalia** [comment]
Fixed in v4.3.6. Thanks for the details 👍
