### ISSUE TITLE
Stream implementation

### ISSUE THREAD

**Issue by LaurensRietveld** [blake-regalia/graphy.js#6]
Is there a reason why this isnt implemented as a stream implementation? I could of course wrap it as such, but was just wondering

**Comment by blake-regalia** [comment]
In which way do you mean? The parsers can be piped to, eg: `fs.createReadStream(file).pipe(graphy.ttl.parse(...))`. They can also be used as a [transform](https://github.com/blake-regalia/graphy.js#graphy-ttl-parse-transform). They *don't* support objectMode and they *do not* implement EventEmitter for performance reasons.

**Comment by LaurensRietveld** [comment]
Ah, great to see that it will support the eventemitter.
About the piping: I couldnt test it properly yet because of the other issues, but it seems I _have_ to provide a data handler that pushes this onward right? 

Reason I asked this, is that I expected this to simply work:
```
fs.createReadStream('./somefile').pipe(graphy.nq.parse())
```
Where it returns the error:
```
TypeError: Cannot read property 'data' of undefined
```
I could of course add the `data` field and push things to the next stream, as described in the README. But then I'm not sure how to deal with error handling and closing of streams in this context. But guess the latter items should be solved with the EventEmitter improvements?

**Comment by blake-regalia** [comment]
Rather than binding events via `.on('eventName', function handler(){...})`, they are attached by the config object [passed to graphy](https://github.com/blake-regalia/graphy.js#parse-events). So for your case, you could do:
```
fs.createReadStream('./somfile').pipe(graphy.nq.parse({
    ready() {
        // stream is readable
    },
    data(quad) {
        // ...
    },
    error(parse_error) {
        // ...
    },
    end() {
        // end of stream
    },
});
```

**Comment by blake-regalia** [comment]
Fixed/improved in latest version. Readers now act as node.js Transforms that can be piped in utf8-encoded strings on their writable side and push RDFJS Quad objects on their readable side.
