### ISSUE TITLE
Cannot parse NQ file where statement has a datatype and no graph

### ISSUE THREAD

**Issue by LaurensRietveld** [blake-regalia/graphy.js#9]
The nq parser won't parse this:
```
<somesub> <somepred> <http://brt.basisregistraties.overheid.nl/def/top10nl#bronactualiteit> "2014-01-01"^^<http://www.w3.org/2001/XMLSchema#string> ..
```
Error: 
```
TypeError: Cannot read property 'substr' of undefined
```

Removing the datatype is a workaround.

The nt parser works fine.

**Comment by blake-regalia** [comment]
Seems like this example showed a quad with a literal in the graph position.

Anyways, [`@graphy/content.nq.read`](https://www.npmjs.com/package/@graphy/content.nq.read) now passes all specification tests.

[API available here](https://graphy.link/content.textual#verb_read).

```js
const nq_read = require('@graphy/content.nq.read');

nq_read('<somesub> <somepred> "2014-01-01"^^<http://www.w3.org/2001/XMLSchema#string> <http://brt.basisregistraties.overheid.nl/def/top10nl#bronactualiteit> .', {
  data(g_quad) {
    // ...
  },
});
```
